wip

diff --git a/geomesa-accumulo/geomesa-accumulo-tools/bin/geomesa-accumulo b/geomesa-accumulo/geomesa-accumulo-tools/bin/geomesa-accumulo
--- a/geomesa-accumulo/geomesa-accumulo-tools/bin/geomesa-accumulo
+++ b/geomesa-accumulo/geomesa-accumulo-tools/bin/geomesa-accumulo
@@ -25,6 +25,24 @@ if  [[ $1 = configure ]]; then
   exit
 fi
 
+function load_classpath() {
+  CLASSPATH="$(get_classpath)"
+  # load and check required dependencies - skip if classpath is explicitly set
+  if [[ -z "$GEOMESA_CLASSPATH" && "$GEOMESA_CHECK_DEPENDENCIES" = "true" && -f "${GEOMESA_CONF_DIR}/dependencies.sh" ]]; then
+    . "${GEOMESA_CONF_DIR}/dependencies.sh"
+    includes="$(dependencies $CLASSPATH)"
+    check_classpath "$GEOMESA_LIB" "$CLASSPATH" "$includes"
+    RET=$?
+    if [[ $RET -eq 1 ]]; then
+      # downloaded new jars - re-load the classpath to pick them up
+      CLASSPATH="$(get_classpath)"
+    elif [[ $RET -ne 0 ]]; then
+       # error or cancelled
+      exit $RET
+    fi
+  fi
+}
+
 # setup the classpath
 function get_classpath() {
   if [[ -n "$GEOMESA_CLASSPATH" ]]; then
@@ -47,7 +65,6 @@ function get_classpath() {
 }
 
 RUNNER="org.locationtech.geomesa.accumulo.tools.AccumuloRunner"
-CLASSPATH="$(get_classpath)"
 
 # set java process options - do this after set classpath b/c that can modify JAVA_LIBRARY_PATH
 if [[ $1 = debug ]]; then
@@ -58,32 +75,33 @@ else
 fi
 
 if [[ $1 = classpath ]]; then
-  echo $CLASSPATH | tr ':' '\n' | sort
+  echo "$(get_classpath)" | tr ':' '\n' | sort
 elif [[ $1 = scala-console ]]; then
   shift 1
   # scala console requires options to be passed in through java_opts
   export JAVA_OPTS="${GEOMESA_OPTS}"
-  geomesa_scala_console ${CLASSPATH} "$@"
-else
-  # load and check required dependencies - skip if classpath is explicitly set
-  if [[ -z "$GEOMESA_CLASSPATH" && "$GEOMESA_CHECK_DEPENDENCIES" = "true" && -f "${GEOMESA_CONF_DIR}/dependencies.sh" ]]; then
-    . "${GEOMESA_CONF_DIR}/dependencies.sh"
-    includes="$(dependencies $CLASSPATH)"
-    check_classpath "$GEOMESA_LIB" "$CLASSPATH" "$includes"
-    RET=$?
-    if [[ $RET -eq 1 ]]; then
-      # downloaded new jars - re-load the classpath to pick them up
-      CLASSPATH="$(get_classpath)"
-    elif [[ $RET -ne 0 ]]; then
-       # error or cancelled
-      exit $RET
+  geomesa_scala_console "$(get_classpath)" "$@"
+elif [[ $1 = ng-stop ]]; then
+  ${%%gmtools.dist.name%%_HOME}/bin/ng ng-stop
+elif [[ "$GEOMESA_NG_ENABLED" = "true" ]]; then
+  # check to see if the nailgun server is up
+  ${%%gmtools.dist.name%%_HOME}/bin/ng ng-version >/dev/null 2>&1
+  RET=$?
+  if [[ $RET -ne 0 ]]; then
+    # it's not running, start the nailgun server
+    load_classpath
+    get_nailgun_options # need to use global state to pass the array for correctly handling quotes
+    coproc ngfd { java $GEOMESA_OPTS -cp $CLASSPATH org.locationtech.geomesa.tools.utils.NailgunServer "${NG_OPTS[@]}"; }
+    IFS= read -r -d '' -u "${ngfd[0]}" ng_output 2>/dev/null
+    echo $ng_output
+    if [[ -z $(echo $ng_output | grep started) ]]; then
+      echo "Error starting Nailgun server"
+      exit 1
     fi
   fi
-
-  # invoke the main java process
-  if [[ $1 = ng ]]; then
-    java ${GEOMESA_OPTS} -cp ${CLASSPATH} com.facebook.nailgun.NGServer
-  else
-    ${%%gmtools.dist.name%%_HOME}/bin/ng $RUNNER "$@"
-  fi
+  # invoke the nailgun client
+  ${%%gmtools.dist.name%%_HOME}/bin/ng $RUNNER "$@"
+else
+  load_classpath
+  java $GEOMESA_OPTS -cp $CLASSPATH $RUNNER "$@"
 fi
